version: "3"
volumes:
  php-fpm-socket:
services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    volumes:
      - ./db/mysql:/var/lib/mysql
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    # restart: always
    ports: ["8888:80"]
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
      - UPLOAD_LIMIT=500M
    depends_on: ["mysql"]

  php:
    build: ./php
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./passcari:/var/www/html:delegated
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
      # - ./php/php-fpm.d/zzz-docker.conf:/usr/local/etc/php-fpm.d/zzz-docker.conf
      # - php-fpm-socket:/var/run/php-fpm
    # depends_on: ["mysql"]

  nginx:
    image: nginx:latest
    volumes:
      # - ./nginx/conf.d/local.conf:/etc/nginx/conf.d/local.conf
      - ./nginx/conf.d/16333509_.ngrok.io.cert:/etc/nginx/16333509_.ngrok.io.cert
      - ./nginx/conf.d/16333509_.ngrok.io.key:/etc/nginx/16333509_.ngrok.io.key
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./passcari:/var/www/html
      - ./nginx/log:/var/log/nginx
    ports: 
      - "80:80"
      - "443:443"
    depends_on: ["php"]

  # ngrok:
  #     image: wernight/ngrok:latest
  #     ports:
  #       - 4040:4040
  #     environment:
  #       NGROK_PROTOCOL: http
  #       NGROK_PORT: nginx:443
  #       NGROK_AUTH: 258dApdKeW0c4WxvHCvpSWenKAJ_3oEUW9zUQCoGBGPVj1XZe
  #     depends_on:
  #       - nginx
  #     networks:
  #       - default
  # queue:
    # build: ./php
    # volumes:
      # - ./apps/cheerup:/var/www/html:delegated
      # - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    # entrypoint: ["php", "artisan", "horizon"]
    # working_dir: /var/www/html

  redis:
    image: redis:latest
    volumes:
      - ./redis/data:/data
    ports:
      - 6379:6379
